---
- name: "Define EzyAdmin API URL for register connector"
  set_fact:
    ezyadmin_register_connector_url: "{{ ezyadmin_api_url }}/external/server/connector/{{ ezyadmin_connector }}/hostname/{{ inventory_hostname }}/register/true"
  when:
    - register_connector

- name: "Main | Register connector to EzyAdmin - Linux"
  uri:
    url: "{{ ezyadmin_register_connector_url }}"
    method: PUT
    status_code: [200,201]
  when: 
    - ezyadmin_register_connector_url is defined
    - ansible_os_family != "Windows"

- name: "Main | Register connector to EzyAdmin - Windows"
  win_uri:
    url: "{{ ezyadmin_register_connector_url }}"
    method: PUT
    status_code: [200,201]
  when: 
    - ezyadmin_register_connector_url is defined
    - ansible_os_family == "Windows"