---
- name: "Define EzyAdmin API URL for register connector"
  set_fact:
    ezyadmin_register_connector_url: "{{ ezyadmin.api_url }}/external/server/connector/{{ ezyadmin.connector_id }}/hostname/{{ ansible_hostname }}/register/true"
  when:
    - register_ezyadmin_connector
    - ezyadmin.api_url is defined
    - ezyadmin.connector_id is defined

- name: "Main | Register connector to EzyAdmin - Linux"
  uri:
    url: "{{ ezyadmin_register_connector_url }}"
    method: PUT
  when: 
    - ezyadmin_register_connector_url is defined
    - ansible_os_family != "Windows"

- name: "Main | Register connector to EzyAdmin - Windows"
  win_uri:
    url: "{{ ezyadmin_register_connector_url }}"
    method: PUT
  when: 
    - ezyadmin_register_connector_url is defined
    - ansible_os_family != "Windows"