---
# Tasks specific for Debian/Ubuntu Systems
- name: "Debian | Include Zabbix gpg ids"
  include_vars: zabbix.yml

- name: "Set short version name"
  set_fact:
    zabbix_short_version: "{{ zabbix_version | regex_replace('\\.', '') }}"

- name: "Debian | Install gpg key"
  apt_key:
    id: "{{ sign_keys[zabbix_short_version][ansible_distribution_release]['sign_key'] }}"
    url: http://repo.zabbix.com/zabbix-official-repo.key
  when:
    - zabbix_repo == "zabbix"
    - ansible_distribution_release != "buster"
  become: yes
  tags:
    - zabbix-agent
    - init

- name: "Debian | Download deb-src repository Ubuntu"
  get_url: 
    url: https://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu/pool/main/z/zabbix-release/zabbix-release_{{ zabbix_version }}-3+bionic_all.deb
    dest: /zabbix-release_{{ zabbix_version }}-3+bionic_all.deb
    mode: '0644'
  when:
    - ansible_distribution == "Ubuntu"
    - zabbix_repo == "zabbix"
  become: yes
  tags:
    - zabbix-agent
    - init

- name: "Debian | Download deb-src repository Debian"
  get_url: 
    url: https://repo.zabbix.com/zabbix/{{ zabbix_version }}/debian/pool/main/z/zabbix-release/zabbix-release_{{ zabbix_version }}-3+bionic_all.deb
    dest: /zabbix-release_{{ zabbix_version }}-3+bionic_all.deb
    mode: '0644'
  when:
    - ansible_distribution == "Debian"
    - zabbix_repo == "zabbix"
    - ansible_distribution_release != "buster"
  become: yes
  tags:
    - zabbix-agent
    - init

- name: "Debian | Installing deb-src repository"
  command: dpkg -i /zabbix-release_{{ zabbix_version }}-3+bionic_all.deb
  when: 
    - ansible_distribution in ['Ubuntu', 'Debian']
    - ansible_distribution_release != "buster"
  become: yes
  tags:
    - zabbix-agent
    - init

- name: "Debian | Download deb-src repository Debian 10"
  get_url: 
    url: https://repo.zabbix.com/zabbix/{{ zabbix_version }}/debian/pool/main/z/zabbix-release/zabbix-release_{{ zabbix_version }}-3+buster_all.deb
    dest: /zabbix-release_{{ zabbix_version }}-3+buster_all.deb
    mode: '0644'
  when:
    - ansible_distribution == "Debian"
    - zabbix_repo == "zabbix"
    - ansible_distribution_release == "buster"
  become: yes
  tags:
    - zabbix-agent
    - init

- name: "Debian | Installing deb-src repository"
  command: dpkg -i /zabbix-release_{{ zabbix_version }}-3+buster_all.deb
  when: 
    - ansible_distribution in ['Ubuntu', 'Debian']
    - ansible_distribution_release == "buster"
  become: yes
  tags:
    - zabbix-agent
    - init


- name: "Debian | Update deb-src repository"
  command: apt-get update
  become: yes
  when: ansible_distribution in ['Ubuntu', 'Debian']
  tags:
    - zabbix-agent
    - init

- name: "Debian | Remove old zabbix-agent"
  command: apt -y remove {{ zabbix_agent_package }} {{ zabbix_sender_package }} {{ zabbix_get_package }}
  when: ansible_distribution in ['Ubuntu', 'Debian']
  become: yes
  check_mode: no
  tags:
    - zabbix-agent
    - init

- name: "Debian | Installing zabbix-agent"
  command: apt -y install {{ zabbix_agent_package }} {{ zabbix_sender_package }} {{ zabbix_get_package }}
  when: ansible_distribution in ['Ubuntu', 'Debian']
  become: yes
  check_mode: no
  tags:
    - zabbix-agent
    - init

#- name: "Debian | Installing deb-src repository Ubuntu"
#  apt_repository:
#    repo: "deb-src http://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu/ {{ ansible_distribution_release }} main"
#    state: present
#  when:
#    - ansible_distribution == "Ubuntu"
#    - zabbix_repo == "zabbix"
#  become: yes
#  tags:
#    - zabbix-agent
#    - init

#- name: "Debian | Installing deb repository Debian"
#  apt_repository:
#    repo: "deb http://repo.zabbix.com/zabbix/{{ zabbix_version }}/debian/ {{ ansible_distribution_release }} main"
#    state: present
#  when:
#    - ansible_distribution == "Debian"
#    - zabbix_repo == "zabbix"
#  become: yes
#  tags:
#    - zabbix-agent
#    - init

#- name: "Debian | Installing deb-src repository Debian"
#  apt_repository:
#    repo: "deb-src http://repo.zabbix.com/zabbix/{{ zabbix_version }}/debian/ {{ ansible_distribution_release }} main"
#    state: present
#  when:
#    - ansible_distribution == "Debian"
#    - zabbix_repo == "zabbix"
#  become: yes
#  tags:
#    - zabbix-agent
#    - init

#- name: "Debian | Installing deb repository Ubuntu"
#  apt_repository:
#    repo: "deb http://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu/ {{ ansible_distribution_release }} main"
#    state: present
#  when:
#    - ansible_distribution == "Ubuntu"
#    - zabbix_repo == "zabbix"
#  become: yes
#  tags:
#    - zabbix-agent
#    - init

# Note: set cache_valid_time=0 to ensure that an apt-get update after the added repo-key
# else you often get 'WARNING: The following packages cannot be authenticated!
# See also:
# http://askubuntu.com/questions/75565/why-am-i-getting-authentication-errors-for-packages-from-an-ubuntu-repository

#- name: "Debian | Installing zabbix-agent"
#  apt:
#    pkg:
#      - "{{ zabbix_agent_package }}"
#      - "{{ zabbix_sender_package }}"
#      - "{{ zabbix_get_package }}"
#    state: "{{ zabbix_agent_package_state }}"
#    update_cache: yes
#    cache_valid_time: 0
#  when: ansible_distribution in ['Ubuntu', 'Debian']
#  become: yes
#  check_mode: no
#  tags:
#    - zabbix-agent
#    - init

- name: "Debian > Mint | Installing zabbix-agent"
  apt:
    pkg: "zabbix-agent"
    state: "{{ zabbix_agent_package_state }}"
    update_cache: yes
    cache_valid_time: 0
  when: ansible_distribution not in ['Ubuntu', 'Debian']
  become: yes
  tags:
    - zabbix-agent
    - init

- name: "Debian | Install policycoreutils-python"
  apt:
    pkg: policycoreutils-python-utils
    state: installed
    update_cache: yes
    cache_valid_time: 0
  become: yes
  when: zabbix_selinux

- name: "Debian | Enable the service"
  service:
    name: "{{ zabbix_agent_service }}"
    enabled: yes
    use: service
  become: yes
  tags:
    - zabbix-agent
    - init
    - service
